### ISSUE TITLE
Error: Failed to instantiate provider "helmfile" to obtain schema: fork/exec terraform.d/plugins/darwin_amd64: exec format error

### ISSUE THREAD

**Issue by abdennour** [mumoshu/terraform-provider-helmfile#15]
## Environment

- **terraform** v0.12.28
- **helmfile** : v0.119.0
- **kubectl**  
> client 1.17 (d224476cd0730baca2b6e357d144171ed74192d6)
> server 1.16 (e163110a04dcb2f39c3325af96d019b4925419eb)
- **other TF providers** : 
> provider.aws v2.68.0
> provider.helmfile v0.1.0
> provider.kubernetes v1.11.3
> provider.local v1.4.0
> provider.null v2.1.2
> provider.random v2.2.1
> provider.template v2.1.2

## Issue
Not able to you it in my terraform plan : 

I used these commands to download the plugin and install the binary in the suitable folder/directory : 

```sh
os=darwin
arch=amd64
thirdparty_plugins=terraform.d/plugins/${os}_${arch}
mkdir -p ${thirdparty_plugins}

if [ ! -f "${thirdparty_plugins}/terraform-provider-helmfile_v0.1.0" ]; then
  curl -o ${thirdparty_plugins}/terraform-provider-helmfile_v0.1.0 https://github.com/mumoshu/terraform-provider-helmfile/releases/download/v0.1.0/terraform-provider-helmfile_${os}_${arch}
  chmod a+x  ${thirdparty_plugins}/terraform-provider-helmfile_v0.1.0
fi
```
Then, I imported in my plan : 

```tf
provider "helmfile" {
}
```

Result from terminal stdout when run `terraform validate` : 

```
Error: Failed to instantiate provider "helmfile" to obtain schema: fork/exec /Users/abdennoor/git/repo-infra/terraform.d/plugins/darwin_amd64/terraform-provider-helmfile_v0.1.0: exec format error
```
Even though `terraform version` is able to list the plugin :

```
# terraform version

Terraform v0.12.28
+ provider.aws v2.68.0
+ provider.helmfile v0.1.0
+ provider.kubernetes v1.11.3
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2
```

Do you have a clear documentation how to install it successfully ?

**Comment by mumoshu** [comment]
Please place it under your home dir:

```
$ ls ~/.terraform.d/plugins/darwin_amd64/
terraform-provider-eksctl	terraform-provider-helmfile
```

**Comment by abdennour** [comment]
The issue is not solved.
