### ISSUE TITLE
Cannot manage the state of an AWS Loadbalancer created by nginx ingress helm release

### ISSUE THREAD

**Issue by abdennour** [mumoshu/terraform-provider-helmfile#19]
When helmfile installs the chart `stable/nginx-ingress`, a new Loadbalancer ( AWS ELB) is created in the Cloud provider.
When I run `terraform destroy`, this ELB is **not deleted**.

How can we use helmfile terraform provider to manage the lifecycle of all **kubernetes services** with `Type: Loadbalancer`

**Comment by mumoshu** [comment]
It's your Kubernetes cluster's job to pend the deletion of the service resource until the ELB is deleted. All Helmfile and the helmfile provider does is "triggering" the deletion of the service resource. So, just hold on until your cluster deletes the ELB and the service resource.

Closing this as answered but please feel free to reopen if necessary

**Comment by abdennour** [comment]
Hello @mumoshu , 
could you please wait my confirmation before closing it.

**Comment by mumoshu** [comment]
Would you mind reading my comment at https://github.com/mumoshu/terraform-provider-helmfile/issues/18#issuecomment-660457229?
