### ISSUE TITLE
Error: Provider produced inconsistent final plan

### ISSUE THREAD

**Issue by andrewnazarov** [mumoshu/terraform-provider-helmfile#22]
I've tried the latest version of this provider (taken from the master branch) and found out that some `terraform apply` failed without any reason. I also noticed that the output had changed. It became a bit messy. And there are no errors related to my helmfile manifests or anything else(there shouldn't be as my helmfile manifests remained the same). The error looks like:

```
chart=chartmuseum/system-logs\nComparing release=oval-****,
 chart=chartmuseum/backend\nComparing release=oval-frontend,
 chart=chartmuseum/frontend\nComparing release=oval-saml,
 chart=chartmuseum/saml\nComparing release=monitoring-addon-oval,
 chart=chartmuseum/monitoring-addon\nListing releases matching
 ^oval-stash-backup$\nNo affected releases\nComparing release=security-service,
 chart=chartmuseum/security-service\noval, security-service, Deployment (apps)
 has changed:\n...\n          app.kubernetes.io/instance: security-service\n
 spec:\n        serviceAccountName: security-service\n        containers:\n
 - name: security-service\n-           image:
 \"eu.gcr.io/****/security-service:master-c924f869\"\n+           image:
 \"eu.gcr.io/****/security-service:master-f7e4e237\"\n
 imagePullPolicy: Always\n            envFrom:\n            - configMapRef:\n
 name: security-service\n            ports:\n...\n\nComparing
 release=marketplace, chart=chartmuseum/marketplace\nAffected releases are:\n
 security-service (chartmuseum/security-service) UPDATED\n\nIdentified at least
 one change\n").
 **This is a bug in the provider, which should be reported in the provider's own
 issue tracker.**
```

**Comment by andrewnazarov** [comment]
Further investigation.
I ran it against about 10 environments. The vast majority didn't have changes. 4 of them failed. Of these four:

1. one had spoiled stated (I wanted to test https://github.com/mumoshu/terraform-provider-helmfile/issues/16)
2. two had changes in helmfile state values
3. one had some error in the deployed release

- the second run helped for only **one** env from case N2
- even the second run of `terraform apply` didn't help for the spoiled state case N1. **But**, I then run `terraform apply` with the previous version of the provider without the fix and it helped. So somehow the state was fixed.
- rollback to the previous version of the provider helped for N3(after I fixed issues with the release) and for the remaining env from N2

Subsequent runs with the old version show no errors. But then I tried the latest again and it failed again for the case when some helmfile state values are changed.

I'll try to get some debug later.

**Comment by andrewnazarov** [comment]
Ah, ok the error is:

```
Error: Provider produced inconsistent final plan
 sequence from the end of this expression, leaving just the inner expression.
 When expanding the plan for helmfile_release_set.mystack to include new values
 learned so far during apply, provider "registry.terraform.io/-/helmfile"
 Template interpolation syntax is still used to construct strings from
 produced an invalid new value for .diff_output: was cty.StringVal
```

**Comment by mumoshu** [comment]
Unfortunately I couldn't reproduce this exact issue, but I found some bugs in the code in addition to one reported in #21.

Adding a few fixes, here's what I get from tf plan when I tried to fix a broken helmfile.yaml:

```
  # helmfile_release_set.mystack2 will be updated in-place
  ~ resource "helmfile_release_set" "mystack2" {
      + apply_output          = (known after apply)
        binary                = "helmfile"
      + concurrency           = 0
      ~ content               = <<~EOT
          - v
          + 
            releases:
            - name: myapp2
              chart: sp/podinfo
          +   values:
          +   - image:
          +       tag: "123"
          +   labels:
          +     labelkey1: value1
        EOT
        dirty                 = false
        environment           = "default"
        environment_variables = {
            "FOO" = "foo"
        }
      ~ error                 = "/Users/mumoshu/bin/helmfile: exit status 1\nin ./helmfile-b96f019fb6b4f691ffca8269edb33ffb16cb60a20c769013049c1181ebf7ecc9.yaml: failed to read helmfile-b96f019fb6b4f691ffca8269edb33ffb16cb60a20c769013049c1181ebf7ecc9.yaml: reading document at index 1: yaml: line 2: mapping values are not allowed in this context\n" -> (known after apply)
        helm_binary           = "helm3"
        id                    = "bsboemkllhcmln9d3gfg"
        path                  = "helmfile.yaml"
        selector              = {
            "labelkey1" = "value1"
        }
        values                = [
            jsonencode(
                {
                    name = "myapp"
                }
            ),
        ]
        working_directory     = "."
    }
```

From:

```
      ~ error                 = "/Users/mumoshu/bin/helmfile: exit status 1\nin ./helmfile-b96f019fb6b4f691ffca8269edb33ffb16cb60a20c769013049c1181ebf7ecc9.yaml: failed to read helmfile-b96f019fb6b4f691ffca8269edb33ffb16cb60a20c769013049c1181ebf7ecc9.yaml: reading document at index 1: yaml: line 2: mapping values are not allowed in this context\n" -> (known after apply)
```

You can see...

- The redundant proceeding `v` in your helmfile.yaml resulted in a `helm diff` error BEFORE the fix.
- It's likely to be fixed AFTER you've fixed the helmfile.yaml, according to `~ error = ... -> (known after apply)`

I think this perfectly matches my expectation now. How about you?

**Comment by andrewnazarov** [comment]
@mumoshu With your latest changes, I cannot reproduce it either:). Cool, thank you so much for your effort and passion)

Let's close it then, I will keep an eye on this situation.

**Comment by andrewnazarov** [comment]
Btw, it seems that processing became slower. Not an issue right now just an observation.

**Comment by mumoshu** [comment]
@andrewnazarov Thanks! I've double-checked my latest changes and realized that there was a bug that resulted in unnecessarily calling `helmfile-diff` twice on plan, and helmfile-diff output was not shown on plan.

16dffc4 fixes that and makes planning as fast as before.
Would you mind confirming that?

**Comment by mumoshu** [comment]
@andrewnazarov In f414b5f, I've made internal exclusive lock to be taken not globally but per `working_directory`(if `path` not set) and the directory of the helmfile.yaml(if `path` is set). This might further make plan/apply faster when there are many helmfile_releases and helmfile_release_sets.

**Comment by andrewnazarov** [comment]
With the latest changes, I'm facing another issue filed here: https://github.com/mumoshu/terraform-provider-helmfile/issues/23
