### ISSUE TITLE
Diff is partially hidden for larger outputs

### ISSUE THREAD

**Issue by mnatan** [mumoshu/terraform-provider-helmfile#24]
**terraform-provider-helmfile version**: 
[3df004fb52ba7c30f65d80eb0c3b537e0c4df7eb](https://github.com/mumoshu/terraform-provider-helmfile/commit/3df004fb52ba7c30f65d80eb0c3b537e0c4df7eb)
**helmfile version**: 
helmfile-0.125.0.high_sierra.bottle.tar.gz

## Overview
We are using helmfile for managing [Jenkins helm deployment](https://github.com/helm/charts/tree/master/stable/jenkins).

It uses a very long config map with hundreds of lines of yaml config. 

When we change anything that ends up at the top of the config map, the diff output in `terraform plan` gets trimmed and we can't see the changes.

I can see that @mumoshu tired to address that issue [here](https://github.com/mumoshu/terraform-provider-helmfile/commit/1a477d9d45c5a82847128c6b1c1614f36bc6ddad#diff-769700fba47e9257c615acae835ad9d3R303), however I believe these flags get passed to `helmfile` ([cli ref](https://github.com/roboll/helmfile/blob/master/README.md#cli-reference)), not `helm-diff`.

## Possible causes
* Some go buffer running out of space
* Terraform's character limit on a string property
* Terraform's display strategy for long string properties

## Example output
```
[...]
------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.blue-jenkins.helmfile_release_set.helmfile_release will be updated in-place
  ~ resource "helmfile_release_set" "helmfile_release" {
      ~ apply_output          = <<~EOT
            ep:1.3.6
                  config-file-provider:3.6.3
                  configuration-as-code:1.42
                  configurationslicing:1.51
                  confluence-publisher:2.0.5
[...]
```
Notice the `ep:1.3.6` is clearly a part of a plugin name.

## Possible solutions
* Change `helmfile` to accept diff flags, or at least the context flag, to shorten the output.
* Display a full diff output

## Side note
the diff was easier to read [with color](https://github.com/mumoshu/terraform-provider-helmfile/commit/039b8788210524aad69d1ffd06f15e6a079d4003#diff-769700fba47e9257c615acae835ad9d3R213)

**Comment by mumoshu** [comment]
@mnatan Thanks for reporting and the note!

> the diff was easier to read with color

Thanks for the feedback. Should we add a provider setting like the below to make it configurable?

```
provider "helmfile" {
  # Set to true by default, which reverts https://github.com/mumoshu/terraform-provider-helmfile/commit/039b8788210524aad69d1ffd06f15e6a079d4003#diff-769700fba47e9257c615acae835ad9d3R213 for standard config
  colorHelmfileOutput = false
}

I was assuming when you read terraform output from a program you'd prefer `--no-color`. Apparently it's still useful for humans, right?

**Comment by mumoshu** [comment]
I'll investigate the incomplete diff output issue soon.

**Comment by mumoshu** [comment]
@mnatan I wasn't able to reproduce it so far, but I've fixed an obvious problem in code that must have resulted in the issue.

The fix is available in v0.3.7. Would you mind giving it a shot?

**Comment by mnatan** [comment]
@mumoshu Thanks for a swift reply! I'll test that in a second.

The `colorHelmfileOutput` parameter seems like a good idea 👍

**Comment by mnatan** [comment]
@mumoshu The output is displaying as expected now 👍 

Thanks again for resolving, I am closing the issue.

Still, the coloured output will be useful :)
