### ISSUE TITLE
Double diff in terraform plan

### ISSUE THREAD

**Issue by mnatan** [mumoshu/terraform-provider-helmfile#25]
**terraform-provider-helmfile version**: 
[v0.3.8](https://github.com/mumoshu/terraform-provider-helmfile/releases/tag/v0.3.8)
**helmfile version**: 
helmfile-0.125.0.high_sierra.bottle.tar.gz

## Overview
When running on this version for the first time the diff_output behaves as expected, displaying no-color diff between previous and current helm deployment.

However, this diff persists in state file and the following terraform plans run the same diff, and diff it with previous diff. 

![diffs](https://user-images.githubusercontent.com/8760540/88940850-9414d580-d288-11ea-803d-0f5a74b944b7.jpg)

## Example output

Full output:
![Screen Shot 2020-07-30 at 17 18 22](https://user-images.githubusercontent.com/8760540/88941157-f968c680-d288-11ea-9eed-5fa34c55f4bf.png)

Extreme example:
![Screen Shot 2020-07-30 at 17 23 58](https://user-images.githubusercontent.com/8760540/88945257-0f2cba80-d28e-11ea-83bc-a891feacc4e4.png)

## Possible causes
* Terraform compares the helm diff with the output of previous helm diff in state file.

## Possible solutions:
* Suppress the diff with [DiffSuppressFunc](https://www.terraform.io/docs/extend/schemas/schema-behaviors.html#diffsuppressfunc) schema function and display it in another way
* Use [StateFunc](https://www.terraform.io/docs/extend/schemas/schema-behaviors.html#statefunc) schema function to always set diff value to empty string or nil in state file. I am not sure if this will print the current version of the diff though.
* Alternatively, terraform sdk provides `customdiff` package that can give a full control over this behaviour. [Resources - Customizing Differences](https://www.terraform.io/docs/extend/resources/customizing-differences.html).

**Comment by PCatinean** [comment]
There was a conversation about this already and @mumoshu suggested on using helmfile template on the output of terraform in order to see the actual diff.

**Comment by mnatan** [comment]
@PCatinean I can't find @mumoshu's suggestion you are referring to, can you please elaborate or give me a link?

**Comment by mnatan** [comment]
Update: Possible solution added to description

**Comment by mumoshu** [comment]
@mnatan Actually this is what happens when we use `customdiff`. I'll try `StateFunc` later.

In the conversation mentioned by @PCatinean, I said that this is unavoidable due to the nature of terraform plan.

We need to use `customdiff` to not break `terraform plan`, but that results in terraform showing the diff for the latest helmfile diff output against the previous helmfile diff stored in the tfstate.

That's why I suggested we'd better use helmfile template instead so that terraform can use that to show changes in manifests.

After that, `diff_output` can be just removed, or renamed to `changes`, so that it is clear that terraform is showing "diff of changes"(this is the purpose of current `diff_output`, which is confusing), rather than "changes in the manifests"(this might be `diff` you'd expect)

**Comment by mnatan** [comment]
Unfortunately, comparing helmfile templates is not enough for us, as they just contain references to values files. Almost all of our changes will happen in these external files.

**Comment by mumoshu** [comment]
@mnatan `helmfile template` is the command that renders K8s maniefsts files, not `helmfile.yaml` templates. Sorry about the confusion but that's what I mean.

Anyway, diffing `helmfile template` results in the provider means that it needs to somehow obfuscase diff on secrets data/stringData, cuz they contain sensitive data. This is currently done in helm-diff which is called by helmfile-diff. That makes implementation a bit more difficult.

**Comment by mumoshu** [comment]
@mnatan I've managed to "fix" this in the way described in the comment in 42a710d13683066174e47b28b7bde9d31fb85ee3

I've cut v0.3.9 for that. Would you mind testing it out?

**Comment by mnatan** [comment]
Works perfectly :)

![Screen Shot 2020-07-31 at 14 09 14](https://user-images.githubusercontent.com/8760540/89033675-a13ccd80-d337-11ea-9d5e-19881fdfd63a.png)

Nice idea to override that on resource read 👍

**Comment by mumoshu** [comment]
@mnatan Thank you so much for the detailed report and sharing possible solutions! I couldn't have done it so fast without those 🙏
