### ISSUE TITLE
Best-practices for secrets management

### ISSUE THREAD

**Issue by joshes** [mumoshu/terraform-provider-helmfile#27]
Hi! I'm trying to fit this into our _existing_ ecosystem. I currently have Terraform built/managed infrastructure and manually put values into a "values" and "secret" yaml (using helm-secrets). I'd like to utilize this plugin so I don't require manual intervention at all and perhaps could remove helm-secrets outright.

Is there a way to pass Terraform derived secrets into a Release Set resource? Is there a better way? Perhaps intermediate files written by Terraform and subsequently used in Helmfile?

Maybe I'm missing something. I would have expected to do something like:

```
# Won't run as-is but to illustrate my point ... 

provider mysql {}
provider aws {}
provider helmfile {}

resource "mysql_database" "default" {
  name = "my_awesome_app"
}

resource "aws_s3_bucket" "default" {
  bucket = "my-tf-test-bucket"
}

resource "helmfile_release_set" "default" {
  # helmfile.yaml already uses environmental defaults for access keys, common configs, etc.
  path = "../helmfiles/helmfile.yaml"
  environment = "production"
  selector = {
    name = "some-app"
  }
  values = [
    s3_bucket = aws_s3_bucket.bucket
  ]
  secrets = [
    mysql_password = mysql_database.password
  ]
}
```

I'm just trying to figure out how best to bridge Terraform created values/secrets with Helmfile and in particular this plugin.

**Comment by mumoshu** [comment]
@joshes Hey! Thanks for trying the provider. I'd suggest using either `environment_variables` or `values` so that it looks like:


```
resource "helmfile_release_set" "default" {
  
  # Accesible via `{{ .Values.mysql.password }}` from within your helmfile.yaml
  values = [
    		<<EOF
mysql:
  password: ${mysql_database.password}
EOF
  ]

  # Accesible via `{{ env "MYSQL_PASSWORD" }}` from within your helmfile.yaml
  environment_variables = {
    MYSQL_PASSWORD = mysql_database.password
  }
}
```

**Comment by joshes** [comment]
Thanks for the quick response! That does indeed look like the right way forward - docs are very clear from that point forward so I'll go ahead and close this out.

Thanks again!
