### ISSUE TITLE
Error finding temp value files

### ISSUE THREAD

**Issue by BuckinghamIO** [mumoshu/terraform-provider-helmfile#50]
Since upgrading to the latest version being 0.12.0 of the provider I've been blocked by the following errors:

```
15:57:15  in ./helmfile-3dce096a66df5e8515ae85f40bd83a2bc10620b819f7b5c0019505065acd204d.yaml: in .helmfiles[0]: in helmfile/releases/00-frontend-helmfile.yaml: 4 errors:
15:57:15  err 0: failed processing release certificate-manager-qa: open .terraform/helmfile/temp-6b9c6545fb/cert-manager-certificate-manager-qa-values-85674b986f: no such file or directory
15:57:15  err 1: failed processing release ingress-external-qa: open .terraform/helmfile/temp-6b9c6545fb/ingress-ingress-external-qa-values-678fb9d8b6: no such file or directory
15:57:15  err 2: failed processing release ingress-internal-qa: open .terraform/helmfile/temp-6b9c6545fb/ingress-ingress-internal-qa-values-5d6d7bfdfb: no such file or directory
15:57:15  err 3: failed processing release external-dns-qa: open .terraform/helmfile/temp-6b9c6545fb/qa-external-dns-qa-values-5bbbb6548b: no such file or directory
15:57:15  
```

If I revert back to 0.11 version of the provider I can run the helmfile perfectly fine.

Versions:
- Terraform 1.14.3
- Helmfile provider: 0.12.0
- Helmfile: 0.136.0

I was hoping to upgrade to take advantage of the performance improvement from --skip-diff-on-install as raised in my other ticket in regards to slow performance.

It seems no temp values are being generated hence why they cannot be found, rather than a permission issue etc...

**Comment by PCatinean** [comment]
I had the same issue and reverted to 11 just like you did. I had setup a working_directory and content in the provider but i got the same error.

**Comment by BuckinghamIO** [comment]
@PCatinean At least It's not just me, fingers crossed @mumoshu can spread some light on the situ as the slack channel didn't bring up any information :/

**Comment by ankitabhopatkar13** [comment]
Facing the similar issue. For me, the temp values file is getting created in the `working_directory` when passed but helmfile diff command cannot find it.

**Comment by mumoshu** [comment]
Everyone, coud you provide me some example tf files and helmfile.yaml you're using for reproduction?

**Comment by ankitabhopatkar13** [comment]
I have two scenarios, one where I get exact same error that @BuckinghamIO mentioned above, in that case my configuration looks like below -

[Scenario-1](https://github.com/ankitabhopatkar13/tf-helmfile-provider-snippets/tree/main/scenario-1) -

`err 1: failed processing release metrics-server: open .terraform/helmfile/temp-6bd584f766/infra-metrics-server-values-5bf6f8598c: no such file or directory

err 2: failed processing release namespaces: open .terraform/helmfile/temp-6bd584f766/kube-system-namespaces-values-6dd565dfd5: no such file or directory`

[Scenario-2](https://github.com/ankitabhopatkar13/tf-helmfile-provider-snippets/tree/main/scenario-2) -

`in helmfile.d/00-namespaces.yaml: environment values file matching "temp.values-2d7cec8dc61849e15ab7ef4822f8572e667ebe1e0ad1208a40cabb8198680362.yaml" does not exist in "."`

In scenario-2 I am trying to use the yaml files from helmfile.d folder which is not provided as an example in the Github repo, so I am not sure if it is expected to work, but it will be great if we can just use the `helmfile.d` folder.

**Comment by mumoshu** [comment]
@ankitabhopatkar13 Thank you so much for your help! Scenario 1 does seem like a regression introduced via https://github.com/mumoshu/terraform-provider-helmfile/commit/389eee7d34b0bd57b8f5b361d98ef7e78822ca33#diff-71e7971f6cba074d43dee961069a3e7b39da40d80d0298e49f0f4ecfd0743aa8R460. Let me try fixing it asap.

Scenario 2 seems to relate to https://github.com/mumoshu/terraform-provider-helmfile/blob/fe22f1206bf39243b1bf6f0eccf2e0a9b0000c19/pkg/helmfile/release_set.go#L205-L209, which would have never worked when you omitted `content` attribute. We assume that helmfile process' work dir matches to `working_directory` attribute but it isn't true when you omitted `content` and helmfile automatically changed work dirs to sub-directories.

The potential fix for Scenario 2 would be to use absolute paths for `--state-values-file` flags so that helmfile ran by the provider is able to find the values files regardless of in which directory it runs.

**Comment by ankitabhopatkar13** [comment]
Thanks @mumoshu for the quick reply!

**Comment by mumoshu** [comment]
@ankitabhopatkar13 @BuckinghamIO @PCatinean I've successfully reproduced Scenario 1 with helmfile v0.137.0 and Scenario 2 with an older version of helmfile, and adding confirmed fixes via #53.

**Comment by mumoshu** [comment]
v0.13.3 has been released for #53.
Would you all mind testing it out?

**Comment by PCatinean** [comment]
@mumoshu will do. Any idea how long it takes to get published on terraform registry?

**Comment by ankitabhopatkar13** [comment]
@mumoshu Confirming that scenario 2 works with the new provider version.

@PCatinean I am using the provider from the [registry](https://registry.terraform.io/providers/mumoshu/helmfile/latest?pollNotifications=true). :)

**Comment by PCatinean** [comment]
It was not published when I checked, tried now and it works great, did not change anything to my setup :+1: thank you for the fix @mumoshu

**Comment by varunpalekar** [comment]
Thanks @mumoshu

**Comment by BuckinghamIO** [comment]
Thanks @mumoshu, highly appreciated!
