### ISSUE TITLE
Advantage over helm provider?

### ISSUE THREAD

**Issue by dudicoco** [mumoshu/terraform-provider-helmfile#6]
Hi,
I've been using helmfile standalone without terraform and I think it's great!
However, when using terraform to trigger helm releases, what advantage does helmfile gives us besides the diff output?
In addition, it appears that when deploying a release for the first time we I don't get the diff output, only one the deployed release is changed I get the diff output.

Thanks

**Comment by andrewnazarov** [comment]
Speaking of our cases, it allows us to get some information from the cluster, such as external IP addresses, and render helmfiles against it.

**Comment by mumoshu** [comment]
@dudicoco helmfile provider gives you advaned features like sourcing values from external sources backed by [vals](https://github.com/variantdev/vals), reusing existing helmfile.yaml maintained within your organization and [the community](https://github.com/cloudposse/helmfiles), patching manifests produced by the release before installing, etc. :)
