### ISSUE TITLE
helmfile diff is run twice against the old tf state and the new one

### ISSUE THREAD

**Issue by andrewnazarov** [mumoshu/terraform-provider-helmfile#9]
The main thing is that `terraform-helmfile-provider` executes `helmfile diff` twice - for the old tf state and for the new one. Errors from the first run might be really confusing and cryptic. And it is not obvious what's going on and why these errors appear.

This seems to be a conceptual problem. Although it's possible to use this provider (and we are pretty happy with it), sometimes strange things might hit you.

The most obvious case is when you want to rename your helmfile or reorganise directory structure.

Say, you'd like to move from
```
resource "helmfile_release_set" "mystack" {
    path = "./helmfile.yaml"
...
}
```
to
```
resource "helmfile_release_set" "mystack" {
    path = "./new_path/helmfile.yaml"
```

It fails during `terraform plan` with
```
specified state file helmfile.yaml is not found
```

Since the provider runs `helmfile diff` using values stored in terraform state first, it won't find the old file (./helmfile.yaml). Therefore, if you need to rename or move a file you have to have two copies of it for a while.

Another case is when one wants to use environment variables or values. There might be some strange errors related to the fact that helmfile.yaml will be rendered using old environment variables or values taken from the state, but not those which you defined in main.tf file.

The same is for values files and their names and so on.

**Comment by mumoshu** [comment]
@andrewnazarov Hey! Thanks. I was under the impression that we could change the way it's persisted in the tf state.

That is - how about changing it to not refer to a file path, but the file content?

```
resource "helmfile_release_set" "mystack" {
    content = file("./helmfile.yaml")
...
}
```

This way, the content of `./helmfile.yaml` at the previous run would be saved in the tfstate and therefore make the annoying `specified state file helmfile.yaml is not found` error disappear.

WDYT?

**Comment by andrewnazarov** [comment]
Yes, this seems to be a much better approach. And also this will help to mitigate all other issues, not only `file not found`.

**Comment by mumoshu** [comment]
@andrewnazarov Great! Thanks for confirming.

You can use `content` today. It has slipped my mind but I just realized that `content` was there since the very beginning of this project.

Also I've updated REAMDE accordingly.

**Comment by andrewnazarov** [comment]
@mumoshu I'm thinking about values files, even though we don't use this construction.

```
# State values files to be passed to Helmfile
    values_files = [
      "overrides.yaml",
    ]
```

I might be wrong, but this can be a problem if we want to rename or move it. Therefore, it's better to advocate against this approach and use inline values instead or to consume content like it's done for helmfile.yaml. 

What do you think?

**Comment by mumoshu** [comment]
@andrewnazarov Hey! Yes, I believe you're absolutely correct.

We already have `values` that should be usable for that.

So I'd suggest updating our README to only mention this way:

```
# State values files to be passed to Helmfile
    values = [
      file("overrides.yaml"),
      file("another.yaml"),
    ]
```

Does it sound good to you?

**Comment by andrewnazarov** [comment]
@mumoshu , yes. I've updated the README. Will try this out when I have a case.

Thanks!

**Comment by andrewnazarov** [comment]
>You can use content today. It has slipped my mind but I just realized that content was there since the very beginning of this project.

I was trying this out and the transition from `path` to `content` worked not that great to me.

I saw the content of my file added in diff, but then I also encountered the error:

```
Error: /usr/local/bin/helmfile: exit status 1
 no state file found. It must be named helmfile.d/*.{yaml,yml}, helmfile.yaml, or charts.yaml, or otherwise specified with the --file flag
```

I turned on debug and I don't see the file name that should be passed to the helmfile command.

I cleared up the TF state from existed resources and tried again with the clean state. Same error:

```
 Error: /usr/local/bin/helmfile: exit status 1
 no state file found. It must be named helmfile.d/*.{yaml,yml}, helmfile.yaml, or charts.yaml, or otherwise specified with the --file flag
```

**Comment by andrewnazarov** [comment]
It seems I found out what is the problem

**Comment by andrewnazarov** [comment]
@mumoshu here is the PR that should deal with this: https://github.com/mumoshu/terraform-provider-helmfile/pull/14

**Comment by andrewnazarov** [comment]
It's working for us now.

**Comment by andrewnazarov** [comment]
Now we can close this, I think.
